### ISSUE TITLE
No Entries in Book

### ISSUE THREAD

**Issue by Fortist** [phantamanta44/Tinkers-MEMES#11] opened 2019-10-13 14:40 UTC
The book has none of this mod's modifiers in it.
You asked the other guy for a screenshot but whats the point of a screenshot with picture of nothing in it?

**Comment by phantamanta44** [comment] 2019-10-13 18:56
currently flooded with schoolwork, will get back to this soon.

for the time being, can you provide the forge version and a list of installed mods and their versions?

**Comment by phantamanta44** [comment] 2019-11-08 23:38
i just tested on the latest version of mantle/tcon/conarm and am unable to reproduce. please get back to me with more info when you can. thanks

**Comment by Protheus** [comment] 2019-11-09 12:23
Updated all files to latest, and I see also no entries in the book. I do not have conarm installed.But will add it and see if that makes a difference

- TConstruct-1.12.2-2.13.0.171
- Mantle-1.12-1.3.3.55
- Mekanism-1.12.2-9.8.2.389
- MekanismGenerators-1.12.2-9.8.2.389
- MekanismTools-1.12.2-9.8.2.389
- tmemes-1.12.2-1.0.8

Here it will say that after Direct the Electromechanical is next
![2019-11-09_08 47 48](https://user-images.githubusercontent.com/1455178/68528502-c2feac00-02f3-11ea-9662-e9b9327ce5cb.png)

No description of the module
![2019-11-09_08 47 52](https://user-images.githubusercontent.com/1455178/68528503-c2feac00-02f3-11ea-8a08-fc1badf49f27.png)

**Comment by phantamanta44** [comment] 2019-11-09 15:23
i need a full mod list, please; other tinkers' addons might be interfering with my book entries

**Comment by Protheus** [comment] 2019-11-11 15:06
apologize for the missing info: https://pastebin.com/yGESR3er
I took Enigmatica 2: Expert and added some additional mods, but kept the rest the same

**Comment by phantamanta44** [comment] 2019-11-11 20:33
turns out Tinkers' Complement was doing something really funky with the book. should be fixed in 1.0.9: <https://www.curseforge.com/minecraft/mc-mods/tinkers-memes/files/2826019>

**Comment by phantamanta44** [comment] 2019-11-11 20:33
clicked wrong button lol

**Closed as completed by phantamanta44** 2019-11-11 20:33 UTC
